language: python
python:
- '3.8'
install:
- pip install -r requirements-dev.txt
script:
- black . --check --exclude=".venv/|node_modules"
- isort --check-only *.py **/*.py
deploy:
  - provider: heroku
    api_key:
      secure: CWxia243cry1+T+bG/w156nzDL/yi1xRafr9dkBNOfbgdcGPxm+5icrVQFbNBxpamFJkp4LPBrhwsui4G1X+XUMiVvznptI6U6Mw9EQ4p8A7F4Z4ChjSs6tccza5M/Yj2lHv4YrHcNOBA4Pv1hemTfS5gRWuaMo2wRtl+ya9+45xm5Xud++nKzmanycTA7/+2oHs1yBCgURtfbM16W3uNP31bZVHndg9vEad7N7cOx7NE0XEcnlNUCDCwYkhPVFyqw76PhTL9UWAfkWNxxn8kTOjy+UKKzd4nCFGV0NkXbce6Diko8sO8DDMJQwsVWnRzkhkvKF5CgaNAu1zAr0HCqwGYBGnrKBlLe61x6trj4v9X7FLgRy3NTMjq1NJgegOdv/dif8qHkeHfm3IbRV+M7+3J0e7n4CJxPc30hw/qnMTUHaR0C0BMx4HTkvvHRvjSNow+A8CEjvqTDiaDdEmVtuKvtSzWkM9HmL/q4jtNzpUqZ9dB09rJqrSLw1x6zxlxx1QJip2j8bnsys3l8YaLt2kKW1EHaOEgylgeaYAtmnZnFA2TbGz6Mof+w91YY5SnOBH1WwbybrttGga242MEXmohrdslL1i14s6Bnt6Q3oDKWTx7utr/Sxt5k3dVT07ralp8S0zU0HjO9YBtoOR3nluNdSJi9s5Nryycij7X/4=
    app:
      master: caption-maker-app
